language: cpp
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - clang-3.7
      - cmake
      - cmake-data
      - g++-5
      - gcc-5
      - lcov
      - libhdf5-serial-dev
      - libpng-dev
      - libboost-all-dev
      - libfftw3-dev
install:
  - git submodule init
  - git submodule update
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - export CXXFLAGS="-coverage"
compiler:
  - clang
  - gcc
before_script:
  - cmake -DCMAKE_BUILD_TYPE=Debug .
script:
  - make check VERBOSE=1
after_success:
  - bash <(curl -s https://codecov.io/bash)
